apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-v3
  template:
    metadata:
      labels:
        app: jenkins-v3
    spec:
      containers:
      - name: jenkins-v3
        image: sihyuk11/jenkins:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 9987
